### ISSUE TITLE
tablet capability requested

### ISSUE THREAD

**Issue by hrisgirl** [jptrsn/zip-captions#44]
I am the Media Director for a small church who is currently using Web Captioner to supply captions for one of our congregants who is deaf. Web Captioner was able to create an add-in to allow the captions to be displayed on a tablet so our member can sit anywhere in the sanctuary during service. Since WC is being sunset the end of October I started researching options and ZipCaptions seems to be the best solution for us however I am hoping you will be able to add the tablet viewing capability so we can continue to give our member the freedom to sit in the congregation without being tied to the Media Booth. 

I would love to have a conversation with you about this.

**Comment by jptrsn** [comment]
Your request comes at a very convenient time - we are planning on releasing our peer-to-peer "sharing" feature tomorrow. This will allow one person to use zip captions as it currently exists, but by using the "sharing - broadcast" feature, it will allow others to view the captions by entering a "session ID" and a "join code."

I would still really like to hear about your experience with zip captions, especially once we get this feature out, so that I can ensure it meets your needs and provides the best accessibility that we can. I will respond here with an update once the broadcast feature has launched, and ask you to try it out and let us know how it works.

Thanks for opening an issue. It's great to hear from folks who are using the tool.

**Comment by jptrsn** [comment]
@hrisgirl We have now released the sharing feature, we will continue to make improvements to ensure that connectivity is stable over long durations. Right now, if the connection to the signal server is broken during a broadcast, new connections do not work as expected. We will also be adding a few other improvements, expect to see them appear over the course of the next couple weeks.

To use the sharing feature, first go on the device which will be listening to the audio, use the menu to select "Sharing," then click the "Start Broadcast" button. This will generate a session ID and a join code.

Then, on the tablet, go to zipcaptions, use the menu to select "Sharing," then enter the session ID and join code, and click the button. You should then see the same captions appear on the tablet as appear on the broadcasting device.

Please let me know how it goes. We are aiming to provide the easiest user experience we can, any feedback (positive or negative, the more specific and detailed, the better) will help us immensely!

Take care!

**Comment by hrisgirl** [comment]
Thank your so much. I am excited to start testing this capability and will be sure to provide my feedback.Renée BabineauWonder Lake Bible Church Media DirectorSent from my T-Mobile 4G LTE Device
-------- Original message --------From: Edu_Coder ***@***.***> Date: 8/28/23  1:42 PM  (GMT-06:00) To: jptrsn/zip-captions ***@***.***> Cc: hrisgirl ***@***.***>, Mention ***@***.***> Subject: Re: [jptrsn/zip-captions] tablet capability requested (Issue #44) 
@hrisgirl We have now released the sharing feature, we will continue to make improvements to ensure that connectivity is stable over long durations. Right now, if the connection to the signal server is broken during a broadcast, new connections do not work as expected. We will also be adding a few other improvements, expect to see them appear over the course of the next couple weeks.
To use the sharing feature, first go on the device which will be listening to the audio, use the menu to select "Sharing," then click the "Start Broadcast" button. This will generate a session ID and a join code.
Then, on the tablet, go to zipcaptions, use the menu to select "Sharing," then enter the session ID and join code, and click the button. You should then see the same captions appear on the tablet as appear on the broadcasting device.
Please let me know how it goes. We are aiming to provide the easiest user experience we can, any feedback (positive or negative, the more specific and detailed, the better) will help us immensely!
Take care!

**Comment by hrisgirl** [comment]
Good Morning!
 
I have run a series of tests utilizing the sharing functionality and I am confident your solution will meet our needs however there are 2 changes that would greatly help our ability to communicate with our deaf and hard of hearing members.
 
First, is there a way that we can 'pause' the captions without loosing the sharing session? Because we are a church, we start the service with prayer and announcements before transitioning to musical worship however because of the music, the captions are not accurate. Since the lyrics are on the overhead screen, we would prefer to pause the captions during music to avoid any incorrect captions and then restart captioning for the remainder of the service.
 
Second, would be be able to be setup with a persistent sharing session ID? I have a team of volunteers who may not remember to enter the sharing session when setting up the tablets and if we had a persistent session we could setup the Kiosk app up to go directly to the dedicated session. Additionally, we would be able to provide a web link on our website and in the weekly bulletin so that any of our hard of hearing attendees could join on their personal devices if needed. We are currently paying a small amount monthly for this capability with WebCaptioner and having this ability on ZipCaptions will assure no errors happen should I be away.
 
Thank you so much for providing this solution. I am excited to be able to roll this out live to our congregation.
 
Renee Babineau ***@***.***)
Media Director, Wonder Lake Bible Church

**Comment by jptrsn** [comment]
The "pause" feature is available in the sidebar during broadcast, it should appear at the top of the controls once you've opened it - see the small arrow peeking in from the right side of the screen. This will pause the recognition, and viewers will see a message that the broadcast has been paused. You can click the button a second time on the broadcasting device in order to resume the broadcast.

We will work on setting up a persistent room, but this will take additional time, as it involves quite a bit of additional infrastructure to put together. It is on our immediate roadmap, and may end up being a patreon-supported option so that we can afford to provide a good user experience that's reliable, stable, and high quality.

Thanks for continuing to use the app!
